### ISSUE TITLE
No BitTorrent applications found

### ISSUE THREAD

**Issue by svendsvin** [DavidMoore/ipfilter#10]
I'm running utorrent 2.2.1 but the log says No BitTorrent applications found and after update the ipfilter file is not updated.

**Comment by DavidMoore** [comment]
Thanks for letting me know. I'll find and install that version on a virtual machine and see how best to detect it.

**Comment by DFNCTSC** [comment]
Same issue here, thanks for trying to fix it.
The exact version is µTorrent 2.2.1 (Build 25302) and it is the 'most recommended' client for private trackers. Just for reference the executable should have the MD5 hash of "BB2FCFA2415D0F08653157D8E998D342".
Thanks again. :)

**Comment by playball335** [comment]
Same for me on 3.0.

Thank you.

**Comment by DavidMoore** [comment]
Do you have the portable version installed?

The app will look under the registry **HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\uTorrent**

Do you have that registry key?

I'm having no luck finding 2.2.1 of uTorrent. It's been scrubbed from the internet :)

**Comment by playball335** [comment]
Hello,

Actually I am the one running 3.0 (not portable).  I can provide you with
it if you need it.

**Comment by svendsvin** [comment]
Thanks for looking into it. No I don't have that registry key. And I don't run a portable version. I even doubt there is one. But I can provide you with 2.2.1 version?

**Comment by gibxxi** [comment]
http://www.oldapps.com/utorrent.php?old_utorrent=38

**Comment by daveb3** [comment]
The app will look under the registry HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\uTorrent

Do you have that registry key?

I dont have this Key instead i have this key

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\uTorrent

**Comment by DavidMoore** [comment]
Thanks @daveb3 , looks like a per-machine install instead of per-user. I'll update the uTorrent / BitTorrent checker to look under those other possible locations, and will be in the next update.

**Comment by gendalv** [comment]
same issue with bittorrent 7.6.1

**Comment by DavidMoore** [comment]
Fix applied in latest version (2.1)
