### ISSUE TITLE
Claims to update qBittorrent.ini but doesn't?

### ISSUE THREAD

**Issue by sblessley-bcit** [DavidMoore/ipfilter#19]
Newbie. Installed and ran app; log says 

Updating app qBittorrent v3.2.3
Pointing qBittorrent to C:\Users\scott\AppData\Local\Apps\2.0\Data\MVZLNW9A.7KN\5M6MY5VQ.0L1\ipfi..tion_0000000000000000_0002.0000_dddeb021f71fa879\Data\ipfilter.dat
Updating qBittorent configuration: C:\Users\scott\AppData\Roaming\qBittorrent\qBittorrent.ini
Done. List timestamp: 9/13/2015 6:06:58 AM -07:00

But qBittorrent.ini has no ipfilter info set ("IPFilter\File=", assuming that's the field), and nothing appears in the qBittorrent UI for IP filtering. The ipfilter.dat file *does* exist in the location cited.

If I manually add the ipfilter.dat  with the QbT UI, it works as expected.

There is only one instance of qBittorrent.ini on this system (Win 7 / 64 bit).

**Comment by DavidMoore** [comment]
OK possible fix in version 2.0.0.5, but I've added some additional logging to help pinpoint the problem if it still doesn't work for you.

**Comment by sblessley-bcit** [comment]
Thanks David.
