### ISSUE TITLE
Application Fails to Install

### ISSUE THREAD

**Issue by DWiechert** [DavidMoore/ipfilter#20]
I just downloaded the `Install Now (Click Once)` and it fails to start the application. I have attached the detail log to this issue.
[QJ72XIDA.txt](https://github.com/DavidMoore/ipfilter/files/225025/QJ72XIDA.txt)

**Comment by DavidMoore** [comment]
Hi there. I've updated the page with the new installer.

Please give the new version a try: https://davidmoore.github.io/ipfilter/install/IPFilter.msi

**Comment by DWiechert** [comment]
No luck. When starting the installer, I now get the error:
```
Unable to update the password. The value provided for the new password contains values that are not allowed in passwords.
```
I've attached a screenshot of the error.
![ipfilter](https://cloud.githubusercontent.com/assets/2567382/14660284/ac7d8a62-0669-11e6-8c32-8dd294597172.png)

**Comment by DavidMoore** [comment]
Hello! Were you updating an earlier version, or this a completely new install, you downloaded and ran the installer manually?

**Comment by DWiechert** [comment]
The errors posted are from trying a completely new install.

I originally had version 2.0.6 and it tried to upgrade to 2.1.0. After the upgrade, it never installed anything and kept trying to do the upgrade over and over. After that, I un-installed and tried re-downloading. That is when I logged this issue.

**Comment by DavidMoore** [comment]
Any luck now?

If you're still getting an issue, there should be an IPFilter.log installation log in your temporary directory you could upload for me to look at (i.e. C:\Users\Dan\AppData\Local\Temp\IPFilter.log)

**Comment by DWiechert** [comment]
I just re-downloaded from your link (https://davidmoore.github.io/ipfilter/install/IPFilter.msi) and it seems to have worked. I know have version 2.2.0.0 and it successfully updated.

Thanks for the help.
