### ISSUE TITLE
Please add eMule support?

### ISSUE THREAD

**Issue by Tolerable** [DavidMoore/ipfilter#25]
Can you please add eMule support as a location to update, not just uTorrent? Thanks..

**Comment by DavidMoore** [comment]
I'll look into this

**Comment by ukaszek2nd** [comment]
For what so I ask??? eMule has got auto-update IP filters itself... unless I'm wrong...

**Comment by Tolerable** [comment]
Well from my understanding, it’s not “auto”, it requires a user loading the file every time they want to update it. Finding a working and updated address to get a current ipfilter.dat (or compressed file) file from is often a problem as so many places quit updating their lists. After seeing how well your’s works with uTorrent, I was hoping your small app. would be able to either update eMule’s data directly or at the least perhaps save a local copy to a user defined location that eMule users could then import into eMule. This would give us some piece of mind knowing that it has been updated within the last 6 hours by your app’s auto update feature, for example. II f neither of those are possible, perhaps even just a way to access the current list URL being used that could be copied and pasted into eMule would be a “poor man’s” way of finding that URL, although I would rather have a local list that is current if direct update into eMule is not possible. 

Thanks for the response.

**Comment by Tolerable** [comment]
Follow up: 

Actually I looked closer at your app, and noticed the log file DOES show the URL which can then be copied and used in eMule. However, it requires going into eMule’s Options, clicking the SECURITY tab, then loading the file from the URL. That also does retain history of the last few used URL’s, so that is not really an issue either. So although it’s a hassle to go through the process to update the list in eMule, that is the main reason I was asking for a way to have it auto-update the list. 

Keeping all that in mind that the manual update is already possible, and “Auto-update” is most likely more work then you want to figure out.. would you be able to instead add a “Minimize to System Tray” feature with your app? Much like uTorrent or other programs when closed have the option to move down near the system clock or “hide” and remain open / functional instead of on the main program bar.  I ask because apparently if I close the program it ceases to function and the 6 hour update will of course not happen.  Additionally a “run update on startup” and “close after update” would allow for users to simply schedule a Windows Event to run the program, have it update the list, and close again at whatever time interval they want. Just some thoughts. 

Thanks again.

**Comment by DavidMoore** [comment]
I've implemented this and it's going to be in the next release (within the next week)
