### ISSUE TITLE
Feature request: Display save-to path

### ISSUE THREAD

**Issue by mdmower** [DavidMoore/ipfilter#3]
I use qBittorent, which also supports filter lists (.dat, .p2p, .p2b). I don't mind if IPFilter Updater saves to a uTorrent specific directory, but it would be helpful if after syncing the window could display the full path (with select + copy ability) where the ip list was saved.

**Comment by Akin2Silver** [comment]
I second the ability for custom paths, as older versions of utorrent are not detected and the filter is not copied across. Would be great to have an manual set path in the settings.

**Comment by mdmower** [comment]
Closing after 6yrs without attention
