### ISSUE TITLE
Is this project still being worked on

### ISSUE THREAD

**Issue by JonnyRedHed** [DavidMoore/ipfilter#34]
Are the lists still being sourced weekly.

Could you maybe implement some of all of my suggestions.  Including contacting CHEF-KOCH about also integrating his very hardened ipfilter.

**Comment by DavidMoore** [comment]
Hi Jonny. Yes I haven't abandoned this yet :) I don't have any control over the filter lists themselves so finding a good, current list is definitely helpful. I'll be adding some new list options and getting rid of the old out of date sources too.

**Comment by JonnyRedHed** [comment]
Yes being able to have check boxes so we can uncheck a list if its proving to aggressive as a temp measure.

When I open the app its always on emule list.  iblocklist is the one I assume for torrents, but this can also block some trackers like the mvgroup documentary tracker. And rare seeded/peer torrents.

**Comment by JonnyRedHed** [comment]
The ipfilter lists timestamps are rather old now it might be best to use Chef-Koch's ipfilter list here for the time being until your able top get things updated:  

https://github.com/CHEF-KOCH/NSABlocklist/tree/master/test/ip-filter

**Comment by DavidMoore** [comment]
Thanks @JonnyRedHed . I'm going to include that list as one of the default lists and it will be in the next major update.
