### ISSUE TITLE
Automatic update fails due to github SSL/TLS restrictions

### ISSUE THREAD

**Issue by Rohaq** [DavidMoore/ipfilter#40]
Looks like the automatic update function needs to be... updated.

Github started restricting SSL/TLS connections to reject connections that use TLS 1.0 and 1.1, so anything that wants to connect to Github needs to use TLS 1.2.

Details on how to fix this in C# apps (depending on what version of .NET you're building with) are here: https://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

Resulting error:
`Application update check failed: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.`

**Comment by DavidMoore** [comment]
Well, damn, that's going to be a manual update unfortunately. Very easy patch but people will need to download and run the next installer instead of using the auto update to get to the patched version.

**Comment by Rohaq** [comment]
Yep, it's somewhat ironic.

You're far from the only project affected either, sadly! I'm pretty sure they gave people a few months of notice to get updated ahead of the change - but that relies on devs keeping up to date with the latest Github news.

**Comment by Akin2Silver** [comment]
@DavidMoore do you have any plans to update with the fix? This is by far my favorite IP list updater tool and would love to see it continue.

**Comment by DavidMoore** [comment]
Hi! Yes I'm actually working on it right this minute. The main delay is that I've added a lot of new features, but this had made the options and configuration a lot more complex. So, what I'm doing right now is going to probably leave out the front end for configuring things, just give it a good out of the box list and push an update as soon as I can. Then, the configuration window can come later.

**Comment by DavidMoore** [comment]
This is now fixed but unfortunately people will have to download and run the latest MSI
