### ISSUE TITLE
extra IP filter parsing errors occurred.

### ISSUE THREAD

**Issue by Noruas29** [DavidMoore/ipfilter#43]
I installed 3.0.0 beta1 version.
It works but in qBitorrent I have this error now: "30/11/2018 12:39 - 5509 extra IP filter parsing errors occurred."

**Comment by DavidMoore** [comment]
Thanks. I can see the same error in my logs. I think there's some invalid addresses in one of the blocklists we're downloading, so I'm going to add some validation to correct these or strip these out.
