### ISSUE TITLE
uTorrent opens very slowly after installing IPFilter Updater 3.0.0

### ISSUE THREAD

**Issue by siddharthprabhu** [DavidMoore/ipfilter#45]
I recently migrated from IPFilter Updater v2.2.0 to v3.0.0. After grabbing the latest list using the application, uTorrent which previously used to launch within 3-4 seconds of opening now takes close to 2 minutes. During those two minutes, uTorrent is listed in Task Manager as a background process consuming a relatively high amount of CPU (see screenshot).

![image](https://user-images.githubusercontent.com/39954383/49425700-6f6f0e80-f7c4-11e8-82cf-0ee83ad0d9bf.png)

After the 2 minute-or-so wait, uTorrent finally opens. Checking Task Manager shows that the CPU usage has returned to normal.

![image](https://user-images.githubusercontent.com/39954383/49425810-c07f0280-f7c4-11e8-8266-d8f6c6d488c5.png)

If I delete the ipfilter.dat downloaded by the Updater, uTorrent opens quickly as usual. I never had this problem when using v2.2.0 of the application. I've tried with the MSI package as well as the standalone executable but to no avail. Any ideas how to solve this?

**Comment by DavidMoore** [comment]
The difference now is that the block list is much bigger (about 30MB decompressed). It's a combined list from several sources. So it's going to take torrent clients longer to load that list.

uTorrent is likely blocking everything until it reads in the block list so it's going to look like it's locking up.

I use qBitTorrent and it seems to be pretty smooth when it comes to loading still (it probably loads the list in the background).

We could verify by getting you to manually download an ipfilter.dat and see if that speeds it up again.

**Comment by siddharthprabhu** [comment]
Thanks for the quick response David!

I did what you suggested by grabbing an ipfilter.dat from eMule-Security and uTorrent loaded 216,313 entries from the file (14.2 MB) without any noticeable increase in application load time. Then I tried downloading the ipfilter.dat from the GitHub repository (31.7 MB) and uTorrent took the usual 2 minutes. However, the curious thing is that the number of entries loaded is 273,726; not significantly more than the eMule-Security file.

It seems odd that the GitHub file should take so much longer to load considering that it only contains are only about 25% more entries. Can you please confirm if the number of entries loaded by qBitTorrent is also 273,726?

**Comment by DavidMoore** [comment]
It could actually be related to bug #43 ; uTorrent might be struggling on parses some invalid entries in the lists. I'm going to go through that bug and see which blocklists those entries are coming from, and that might actually fix this one as well.

**Comment by siddharthprabhu** [comment]
Thanks David! I'd be happy to test out the fix for #43 on uTorrent and let you know if it sorts out the loading issue.

**Comment by MartyD23** [comment]
Just opened a ticket (https://github.com/DavidMoore/ipfilter/issues/46) and saw this. 

I have the same issue.

This is too long just to open utorrent.

**Comment by DavidMoore** [comment]
I finally got some time to set up a VM with uTorrent and test I thought that maybe the list was too big, and it's definitely crushing uTorrent. It eventually loads but takes forever.

Narrowing the list down to the previous basic sources seems to make uTorrent happier.

Over the holidays I'll have some time to go through all the list sources and figure out which ones are problematic.

**Fix**: Run IPFilter and update to the latest list (timestamp is for Dec 21st). uTorrent should now open (there's a noticeable CPU spike and delay but it opens in a couple of seconds).

**Comment by siddharthprabhu** [comment]
@DavidMoore Thanks! I confirm seeing the same CPU spike before uTorrent opens but the delay is now down to 4-5 seconds. Definitely much better than before so thanks for looking into this.

Happy holidays!

**Comment by MartyD23** [comment]
I can also confirm this is working a lot better now.

One thing i have noticed, is when the list is updated the ipfilter.dat is about 20mb, but after using utorrent for a bit and opening/closing the program a few times, the list reduces in size to about 14mb.

**Comment by DavidMoore** [comment]
This problem should be pretty much eliminated now; we merge and tidy the list and put it in the desired format, so bit torrent clients should load the list very fast, and not alter the list either.

These fixes are now in 3.0.1 or higher

**Comment by siddharthprabhu** [comment]
@DavidMoore Thanks so much! I just tested with uTorrent 3.5.5 (build 45271) and confirm that this has fixed the loading time problem. CPU usage during application start-up is also normal now.
