### ISSUE TITLE
no updates for quite some time

### ISSUE THREAD

**Issue by nynor** [DavidMoore/ipfilter#5]
i see that the filter file has not been updated since 10/31/2014.  any plans for the file to be updated?

thanks for the hard work.

d.

**Comment by bertans** [comment]
"As for TBG's lists and IP-filters availability: Only IP-filters are being made available at the moment. They're still free and they offer far better file-sharing protection than anything else being offered. The links to those are not being released publicly to prevent ap2p companies from having easy access to them. If you would like to have links to the IP-filters for your personal use, then send an email to tbgblocklists at hushmail dot com requesting this. -Monk"

Maybe this can help! ;)

**Comment by brow419** [comment]
Whats going on im using the latest version 1.0.0.11 and it only updates until 10/31, iblocklist site isnt down im just wondering whats going on?

**Comment by DavidMoore** [comment]
Hi. Yes I think the list it's currently pointing to is out of date and not being updated. I'm getting in touch with the I-Blocklist guys to get a link we can use for free.

A new update is coming fairly soon (within the next week) with lots of changes, including scheduled silent update checks so you don't have to manually run the software. Most of the work is done, but I need to do more testing, and fix up some of the UI.

**Comment by brow419** [comment]
thanks sounds great

**Comment by DavidMoore** [comment]
OK so update is nearly ready to go. I hope to push out the big 2.0 update sometime tonight once I've done some more testing of the software updates.

**Comment by brow419** [comment]
awesome

**Comment by DavidMoore** [comment]
Ok version 2.0 is live. It currently uses the list from here by default: http://emule-security.org/

I will leave this issue open until I can get a link to a free list from I-Blocklist, and also verify that these lists are actually current.

**Comment by brow419** [comment]
thanks for the update but why doesnt it show the info at the bottom, like the date of the file

**Comment by DavidMoore** [comment]
Oops, yes I'll put that back in. I've raised a separate issue: #6 

It might be a bit trickier now, as the emule list doesn't have a proper timestamp or etag coming from the server, so there's no real way to know the date and time.

**Comment by brow419** [comment]
ok thnaks for all your efforts

**Comment by DavidMoore** [comment]
I haven't heard back from the i-blocklist guys, but the default list seems to be updating at the moment. I can't verify if the contents of the list is actually up to date though.

I'll close the issue for now. The availability and freshness of the lists is definitely a concern, but I don't have any control over that, and I can understand the effort those guys put in.
