### ISSUE TITLE
3.0.0 Beta 2 released for 2+ months but download links point to 3.0.0 Beta 1

### ISSUE THREAD

**Issue by DFNCTSC** [DavidMoore/ipfilter#55]
@DavidMoore  http://www.sadrobot.co.nz/ipfilter/changelog/ reads 3.0.0 Beta 2 but the download link points to https://github.com/DavidMoore/ipfilter/releases/download/3.0.0-beta1/IPFilter.msi

Myself and others have made comments about this on your Disqus but no replies.

Hope this was just an oversight. Thanks!

**Comment by DavidMoore** [comment]
Hi! Yes it was a bit of an oversight as I've been organizing the build and release process, but I'm now going to start pushing out updates a bit faster :)

The docs will probably lag behind a bit until I sort that out.

Please let me know ~~if~~ when I mess something up.
