### ISSUE TITLE
Russian path support

### ISSUE THREAD

**Issue by serofir** [DavidMoore/ipfilter#57]
Crashes all the time when run.
![2019-08-12_212430](https://user-images.githubusercontent.com/11831096/62884567-b56b7180-bd58-11e9-85d0-0e25754956f4.png)

Windows 10 LTSB
NetFramework 4.8

**Comment by DavidMoore** [comment]
Hi. Do you know what culture and language Windows is set to? Is it some Cyrillic such as Russian?

**Comment by serofir** [comment]
Yes. It is russian.

**Comment by ValZapod** [comment]
@DavidMoore Hello! I do not want to open a new issue, so excuse me for hijacking))
Does ipfilter (uTorrent) blocks this site from seeing my torrents? https://iknowwhatyoudownload.com/

Thank you very much))

**Comment by DavidMoore** [comment]
@serofir  I've pushed a new release to try and fix a problem with Japanese paths, where the backslashes in paths show up as the Yen symbol due to the Japanese character set. I hope this is related to your issue, and will either fix it also, or at least provide some more information in the log if it still crashes for Russian. Please let me know if the update helps.

**Comment by serofir** [comment]
Thanks so much for trying to help me.
Now the error looks like this -
![new](https://user-images.githubusercontent.com/11831096/64011911-67b77d00-cb3e-11e9-9d38-9eeb405ffef3.png)

**Comment by DavidMoore** [comment]
Hopefully the next release will get you past this error, and either fix your problem or give us more information. https://github.com/DavidMoore/ipfilter/releases/tag/3.0.2.4-beta

**Comment by serofir** [comment]
When I download .exe file, not .msi.
And then I run it.
Everything works fine

IPFilter.exe Information: 0 : Checking for software updates...
IPFilter.exe Information: 0 : Current version: 3.0.2.4-beta
IPFilter.exe Information: 0 : Available version: <no updates>
IPFilter.exe Information: 0 : Found app qBittorrent version v4.1.7 at E:\qBittorrent
IPFilter.exe Information: 0 : Downloading filter from https://github.com/DavidMoore/ipfilter/releases/download/lists/ipfilter.dat.gz
IPFilter.exe Information: 0 : Online filter's timestamp is 05.09.2019 17:02:22 +00:00
IPFilter.exe Information: 0 : ETag: '"f50889d62fffda42554cd0c9d5883b6a"'
IPFilter.exe Information: 0 : Writing cached ipfilter to C:\Users\User\AppData\Local\IPFilter\ipfilter.dat
IPFilter.exe Information: 0 : Updating app qBittorrent v4.1.7
IPFilter.exe Information: 0 : Writing filter to C:\Users\User\AppData\Local\qBittorrent\filter\ipfilter.dat
IPFilter.exe Information: 0 : Finished [Writing 408739 entries] in 00:00:00.7210319
IPFilter.exe Information: 0 : Pointing qBittorrent to C:\Users\User\AppData\Local\qBittorrent\filter\ipfilter.dat
IPFilter.exe Information: 0 : Updating qBittorrent configuration: C:\Users\User\AppData\Roaming\qBittorrent\qBittorrent.ini
IPFilter.exe Information: 0 : Done. List timestamp: 05.09.2019 23:02:22 +06:00

**Comment by serofir** [comment]
Problem resolved.

**Comment by DavidMoore** [comment]
Thanks
