### ISSUE TITLE
Silent updating always installs 0 byte ipfilter.dat file

### ISSUE THREAD

**Issue by IntelliMoo** [DavidMoore/ipfilter#58]
IPFilter v3.0.1-beta
The silent update feature (such as when using the scheduled task) always installs a 0 byte ipfilter.dat file.
Updating manually installs a proper ipfilter.dat file.

**Comment by DavidMoore** [comment]
Hi! Thanks for raising this issue.
Can you please update to v3.0.2  and let me know if this is now working for you?

**Comment by IntelliMoo** [comment]
Quite welcome.  Looks like 3.0.2.3-beta does fix the problem.

Thanks!

**Comment by DavidMoore** [comment]
Cheers!
