### ISSUE TITLE
Can't install 3.0.2.4-beta 'invalid installation package'

### ISSUE THREAD

**Issue by Sammey1995** [DavidMoore/ipfilter#60]
The file 'C:\Users\myusername\AppData\Local\Temp\' is not a valid installation package for the product IPFilter 3.0.1-beta. Try to find the installation package 'IPFilter.msi' in a folder from which you can install IPFilter 3.0.1-beta.

It appears I need the .msi installation file for the old version of it, but I no longer have it. How do I proceed to either get that file, or uninstall it so that I can install the newer version.

**Comment by DavidMoore** [comment]
Were you using the auto-update feature to try and upgrade, or did you manually download the 3.0.2.4-beta installer and run that?

**Comment by DavidMoore** [comment]
You should be able to go to Add/Remove Programs and manually uninstall IPFilter, then download and install the latest MSI from https://github.com/DavidMoore/ipfilter/releases

**Comment by DavidMoore** [comment]
From now on (3.0.2.8), when the auto update runs, it's going to keep the latest installer safe so when you update or uninstall, the installer won't have been yoinked from your temporary directory.

It's a bit strange as I would think Windows caches installers that have been downloaded. I think as the program is a self-contained .exe, I'll look at deprecating the installer in the near future.
