### ISSUE TITLE
Silent update does not download if no torrent app found

### ISSUE THREAD

**Issue by IntelliMoo** [DavidMoore/ipfilter#61]
IPFilter v3.0.2.4-beta
Hi again. An issue I've noticed since I had to change torrent clients, is when updating silently no download occurs. The Logs shows:

IPFilter.exe Information: 0 : Checking for software updates...
IPFilter.exe Information: 0 : Current version: 3.0.2.4-beta
IPFilter.exe Information: 0 : Available version: <no updates>
IPFilter.exe Warning: 0 : No BitTorrent applications found.

I'm currently using Tixati, which can auto reload filters from a file by setting it in its settings, so it can still use the download from IPFilter easily. It's just IPFilter is not downloading silently; manually updating in IPFilter does download the file OK.

**Comment by DavidMoore** [comment]
Thanks, I will look into supporting Tixati directly, and also I'll look at fixing this so that silent update grabs the filter even if no clients are found

**Comment by IntelliMoo** [comment]
Cool, thanks.

**Comment by CaptainFrosty** [comment]
Tixati can pull updated lists from http links natively. I know it supports `.gz` so you could pull the filter straight from this git with a raw link.

**Comment by CaptainFrosty** [comment]
![image](https://user-images.githubusercontent.com/8523498/102898791-05237800-4438-11eb-8d62-6c107d7c40ad.png)
works

**Comment by DavidMoore** [comment]
Separate issue for supporting Tixati natively: #51

**Comment by DavidMoore** [comment]
Fixed in 3.0.4
