### ISSUE TITLE
ipfilter updates

### ISSUE THREAD

**Issue by Rootzpower** [DavidMoore/ipfilter#63]
This is not a issue just a question.

how often lists of ipfilter update?
And what base you use to update it?

Thanks and keep the good work

**Comment by DavidMoore** [comment]
Hi! I have an automated system that combines some online lists each night, so the list "updates" every day. But, updates is in quotes because I haven't had a chance to see how often the source lists (which I don't look after) are updated or if their contents change often.

**Comment by DavidMoore** [comment]
The nightly list is currently just a combination of i-blocklists, which is configured here: https://github.com/DavidMoore/ipfilter/blob/lists/default/lists.json

I used to other another source but that is now defunct, so it's just i-blocklist for now.
