### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by SiTWulf** [DavidMoore/ipfilter#65]
![image](https://user-images.githubusercontent.com/17046378/76456319-92b83e80-63b5-11ea-968e-8585f1ca1aec.png)

Always get a 404 error

**Comment by DavidMoore** [comment]
There was an issue with publishing the latest list to GitHub. I'll keep checking this to make sure it doesn't break again.

**Comment by SiTWulf** [comment]
Tested in the lastest version 3.0.2.9-beta and Works without any problem.

Thanks @DavidMoore
