### ISSUE TITLE
Error message not fitting in GUI (windows)

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [DavidMoore/ipfilter#67]
I use Winaero Tweaker to adjust the default font size in windows 10 & 8.1 to make each font size a little bigger however this can cause issues with some programs not displaying text correctly.
I don't think this is the whole issue here though as the actual error message would not fit on the GUI under any circumstances

![error_path text](https://user-images.githubusercontent.com/55051487/79638708-e3724280-817e-11ea-8089-ef6e2ab11882.png)
the text should be "Could not find a part of the path 'C:\Users\James\AppData\Local\eMule\config\ipfilter.dat'."

**Comment by DavidMoore** [comment]
Fixed in 3.0.4
