### ISSUE TITLE
Lastest Update Blocks RARBG Trackers?

### ISSUE THREAD

**Issue by MartyD23** [DavidMoore/ipfilter#69]
Hi, after recent update RARBG trackers are no longer connecting. Can you please check to see if your filter list is not blocking them? Thanks

udp://tracker.trackerfix.com:82/announce

udp://9.rarbg.me:2720/announce

udp://9.rarbg.to:2760/announce

**Comment by DavidMoore** [comment]
Hi! The list gets updated nightly. Do you have any idea which day this might have started? Is it still happening for you?

**Comment by MartyD23** [comment]
Hi David, sorry i think it may have been problems with the tracker itself and it seems to be working now but occasionally goes offline.
