### ISSUE TITLE
Standalone EXE

### ISSUE THREAD

**Issue by stdedos** [DavidMoore/ipfilter#7]
A portable executable version, with update checking or automatic update.

**Comment by DavidMoore** [comment]
By portable do you mean no install needed i.e. download and unzip / run?

I'll try to roll everything into a single exe as well (may be possible).

**Comment by stdedos** [comment]
Yes that is my wish. If you do not feel like bundling (or if it is
prohibited by 3rd party libraries), get a zipped folder instead. Easily
moving it along is easier to utilize (and you may eliminate supporting eg
Win 2000 or even XP without the use of installer).

**Comment by gendalv** [comment]
dude at least make it a normal 'select folder where to install' installation, rather than a weird hidden folder installation

**Comment by DavidMoore** [comment]
I do have the self-contained EXE working, likely requiring .NET Framework 4.5.

More testing, new installer and update process coming before I can release.

**Comment by DavidMoore** [comment]
Just an update on this; the app is now self-contained .exe requiring .NET 4.5. The new auto-update will come in version 3.0 which is the next update I will push ideally. I will look to make the self-contained exe available for separate download from the homepage and update this issue when that's done.

**Comment by TheOne320** [comment]
Any new info on this?

**Comment by DavidMoore** [comment]
Latest version (2.1) is now a self-contained single .exe.

Right now only the installer is available from the main page, but I'll upload a build of the exe later this week once I add in a way to deal with the auto update process when the app actually isn't technically "installed".

**Comment by TheOne320** [comment]
Been 17 days. Any info?

**Comment by DavidMoore** [comment]
Hi. I've updated the homepage with a link to the self-contained exe at https://davidmoore.github.io/ipfilter/

You will need to unblock the exe in file properties.
