### ISSUE TITLE
Req: please consider consolidating this transmission blocklist

### ISSUE THREAD

**Issue by rugabunda** [DavidMoore/ipfilter#70]
Source: https://github.com/sahsu/transmission-blocklist

This was recommended by the maintainer of oisd, here https://greycoder.com/the-best-blocklist-for-torrents/ there are also other lists on the aforementioned page.

Thank you, and keep up the great work, this is an excellent little application! :)

**Comment by DavidMoore** [comment]
Hi!

I did have a look at some alternate lists, including the ones you mentioned, but they all seem to be using the i-blocklist sources and combining them, which is pretty much what I'm doing already.

Sadly I'm not sure if there's any other alternatives out there.

If you do find anything other than i-blocklist, especially if it's regularly maintained, please let me know and I can add to the list of sources to build the ipfilter list nightly <3
