### ISSUE TITLE
404 Page...

### ISSUE THREAD

**Issue by Volcano74** [DavidMoore/ipfilter#71]
When trying to update **ipfilter.dat** (Windows 10) error - **404: Page Not Found**.

![image](https://user-images.githubusercontent.com/74209549/98588203-26614800-2280-11eb-8692-fa2ec51e2546.png)

**Comment by DavidMoore** [comment]
Well that was weird! For some reason GitHub wasn't allowing the nightly build to upload the latest compressed list. Hopefully that doesn't happen again! But if it does, at least I know how to fix it straight away :D

**Comment by Volcano74** [comment]
A million thanks for taken over so quickly! 
Now, it is working like charm...  
Cheers 🥂

**Comment by DavidMoore** [comment]
Thanks very much for bringing it to my attention! I wish I could have fixed sooner but I couldn't do so at the office.
