### ISSUE TITLE
Settings dialog not being obeyed or displaying properly

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [DavidMoore/ipfilter#72]
The tick box **Schedule automatic background update of list** does not retain my selected preferences, I am unable to determine if it has been selected in the past.

Replication;
In Options place a tick in the box **Schedule automatic background update of list** and Save Settings, close the Options window then reopen it, there is now no tick to denote this preference has been previously activated.

The entry in the Task Scheduler for IPFilter still remains.  Would it be possible to have the tick remain when the Options window is closed and to remove the IPFilter entry from the Task Scheduler when the tick is removed?

**Comment by DavidMoore** [comment]
Fixed in 3.0.4
