### ISSUE TITLE
IPFilter adds task scheduler entry even if it is not enabled when saving settings

### ISSUE THREAD

**Issue by Sopor** [DavidMoore/ipfilter#73]
I downloaded `IPFilter.exe` and ran it. I opened settings and enabled `Disable software update check at startup`, saved it and then i closed the window. If i now open Task Scheduler i can see that IPFilter has now added an entry in the task scheduler and if i open options again the `Schedule automatic background update of list` is now enabled even if it wasn't when i saved the settings.

So it seems that IPFilter will install the scheduler even if i'm not enabling it. I have tried to disable `Schedule automatic background update of list` but it will not remove the entry from the task scheduler. Instead it seems to re-add it to the task scheduler.

In ipfilter.json i can read `"task":{"isEnabled":false}` but in the options window it is enabled.

Windows 10 x64
IPFilter v3.0.2.9-beta

**Comment by Jamesstevens-3rd** [comment]
I already nentioned this
https://github.com/DavidMoore/ipfilter/issues/72

**Comment by Sopor** [comment]
@Jamesstevens-3rd I wasn't sure if your report was the same as mine or not. Your report sounded more like a suggestion/request than an issue.

**Comment by DavidMoore** [comment]
Thanks, I'll cover this is #72 then!
