### ISSUE TITLE
Suggestion - Change Save settings to Save options to make it more consistent

### ISSUE THREAD

**Issue by Sopor** [DavidMoore/ipfilter#74]
No big deal but it could be a bit confusing when you use `Options` in the main window and in the title of the window, but to save it i have to do that on a button called `Save settings`.

I would suggest you to change that button to `Save options` to make it more consistent.

It would also be nice if you could add a close button, because when i press the `Save settings` all the buttons gets grayed out. There is the small X in the upper right corner, but i still believe there should be a real close button :)

![image](https://user-images.githubusercontent.com/5789283/101060093-4d651e00-358f-11eb-8626-678150f3b4a9.png)

**Comment by DavidMoore** [comment]
Fixed in 3.0.4

**Comment by Sopor** [comment]
If i now open options both OK and Cancel buttons are grayed out, so i can't press Cancel if i want to leave.

Cancel shouldn't be grayed out.

![image](https://github.com/DavidMoore/ipfilter/assets/5789283/d7ca68af-ce97-4036-999b-18ee29a65d9c)
