### ISSUE TITLE
Why Does it Need eMule installed?

### ISSUE THREAD

**Issue by amiga-500** [DavidMoore/ipfilter#77]
So when i tried this on my PC it didnt ask for eMule nor do i ever intend to install that antiquated file sharer.  However, on my brother's PC it did require eMule.  So i have to ask, because the docs here are very thin, what is eMule used for by this app?

**Comment by DavidMoore** [comment]
Hi! I'm not sure I understand the question.

This application doesn't need eMule or any particular software installed.

Is your brother's PC perhaps running an old version that would download the eMule Security blocklist? This was a blocklist intended for use with eMule clients but we could use as a good list to use with other clients like uTorrent and qBitTorrent.

**Comment by amiga-500** [comment]
Hi David!  Thanks for the reply.  Some extra info.  I checked with him and you are correct, he used to have eMule installed.  He de-installed it a long ago (years back) but it appears Windows and/or eMUle itself didn't remove all of its registry or possibly %appdata% content when deinstalling.

I figure when installing this app, it got confused and thought eMule was still installed and then subsequently crashed when it didn't find what it needed from eMule.  So you can chalk this up to bad deinstallers.  He ended up just installing eMule again since he doesn't want to bother hunting down registry entries and %appdata% directories related to eMule.  It has solved the ipfilter crash issue now.
