### ISSUE TITLE
How do I even...

### ISSUE THREAD

**Issue by krizman99** [DavidMoore/ipfilter#8]
Update from 1.0.0.11 to 2.0?

**Comment by DavidMoore** [comment]
Hi. If you have a version installed, it should upgrade when you launch. 2.0 onwards should prompt you to upgrade when you launch. Are you not getting anything?

If you wanted to get up and running now, you could try running the installer again.

**Comment by krizman99** [comment]
It wouldn't update from 1.0.0.11.  I had to uninstall that and redownload it again.  It seems to be working fine now, thanks.
