### ISSUE TITLE
ipfilter.dat list last update from 30/7/2022?

### ISSUE THREAD

**Issue by ezrideroftp** [DavidMoore/ipfilter#85]
As per title, just updated the list, but the timestamp of the list is showing as 30/7/2022. Is this the same bug as before where the incorrect timestamps are showing or has the filter list source stopped updating it?

**Comment by zzzpppzzz** [comment]
I am having the same issue..

**Comment by DavidMoore** [comment]
Thanks for raising this! Looking into this now.

**Comment by DavidMoore** [comment]
The list should be fresh and toasty again! Thanks. Sorry for the super late response; I need to check my notifications!

**Comment by ezrideroftp** [comment]
> The list should be fresh and toasty again! Thanks. Sorry for the super late response; I need to check my notifications!

Thanks! No worries, was getting worried that you'd gone or abandoned it so it's nice to know you're still about, supporting this super helpful tool.

**Comment by zzzpppzzz** [comment]
> The list should be fresh and toasty again! Thanks. Sorry for the super late response; I need to check my notifications!

Looks to be working again. Thanks for all your work!
