### ISSUE TITLE
Options saving don't work properly

### ISSUE THREAD

**Issue by AlecClaire** [DavidMoore/ipfilter#89]
Options >- when only the first option is checked "Schedule automatic..." and "Save settings" is clicked it doesn't save the option.

The option "Schedule automatic..." keeps its saved ticked status only if at leat one other option is ticked and saved.

**Comment by p1r473** [comment]
Same issue here

**Comment by DavidMoore** [comment]
Thanks for letting me know. Very silly bug and an easy fix; I will bring this into the next release.
