### ISSUE TITLE
Crashes all the time

### ISSUE THREAD

**Issue by jaycelou** [DavidMoore/ipfilter#9]
Hi.
I just install and it crash every time I open it. Here's the detail,

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IPFilter.UI.exe
  Application Version:	2.0.0.4
  Application Timestamp:	54be0f2e
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.18409
  Fault Module Timestamp:	5315a05a
  Exception Code:	e0434352
  Exception Offset:	000000000000940d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2413
  Additional Information 2:	2413de213f38e5efe700010a55469627
  Additional Information 3:	6b60
  Additional Information 4:	6b60505ed1d3daa9d32dcf371905fb5b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Thanks.

**Comment by DavidMoore** [comment]
Sorry about that. Does this crash before you even see the main window?

Are there any additional errors in your Application Event Log that have more information?

Do you have .NET Framework 4? It looks like you're on Windows 7 (or maybe Server 2008).

**Comment by jaycelou** [comment]
Yes. It crash before I can see any window.
I have copy the entire error message.
I have .net 4 installed.
![Uploading .Net ver.png . . .]()
![Uploading IPFilter crash.png . . .]()

**Comment by jaycelou** [comment]
Any solution yet? I'm waiting!!!

**Comment by DavidMoore** [comment]
Have you checked your Application Event Log? Hopefully it will have a more detailed .NET error in there which can give a clue where the app is crashing.

You could also run Debug View (DbgView) from https://technet.microsoft.com/en-us/library/bb896647.aspx, then launch IPFilter Updater and see if you see anything show up.

You'd expect to see "Initializing..." and "Checking for software updates..." messages, then some messages about detecting installed BitTorrent apps.

I've been pretty busy, so I might come back and put some more work into the install / update and logging parts of the app.

**Comment by jaycelou** [comment]
I've downloaded both the IPFilter.UI.application and setup.exe and try to reinstall, both failed.
Here is what happen with setup.exe:
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.1.1 {version}
Running checks for package '.NET Framework 3.5 SP1', phase BuildList
Reading value 'SP' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.5'
Read integer value 1
Setting value '1 {int}' for property 'DotNet35SP'
The following properties have been set for package '.NET Framework 3.5 SP1':
Property: [DotNet35SP] = 1 {int}
Running checks for command 'DotNetFX35SP1\dotNetFx35setup.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet35SP' and value '1': true
Result of checks for command 'DotNetFX35SP1\dotNetFx35setup.exe' is 'Bypass'
'.NET Framework 3.5 SP1' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://davidmoore.github.io/ipfilter/install/IPFilter.UI.application'.

When I try with IPFilter.UI.application this the error message:
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34209
	System.Deployment.dll 		: 4.0.30319.34209 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfdll.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///D:/IPFilter.UI.application

IDENTITIES
	Deployment Identity		: IPFilter.UI.application, Version=2.0.0.4, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\IPFilter.UI.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [3 Mar 2015 8:58:02 AM] : Activation of D:\IPFilter.UI.application has started.
	* [3 Mar 2015 8:58:02 AM] : Processing of deployment manifest has successfully completed.
	* [3 Mar 2015 8:58:02 AM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [3 Mar 2015 8:58:02 AM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by DavidMoore** [comment]
Looks like a ClickOnce problem / security issue. I'm working on a separate installer, and a standalone exe, which will give you different options for installation. Should have at least one of these done this weekend.

**Comment by jaycelou** [comment]
Thanks. Your hard work is much appreciated! Cheers!

**Comment by DavidMoore** [comment]
Any luck with the new installer? https://davidmoore.github.io/ipfilter/install/IPFilter.msi
